### PR TITLE
Internationalization and multi track support

### PR DESCRIPTION
**Pull request by Wilkins**
Hi Stefano,

Here is my latest contribution.
I added the following features :
- Internationalization : English, French, Italian (The current version is the english one, I hope you can translate it)
- Multi track support : this allows to handle multi track files, check/uncheck the tracks on the map, and export the visible tracks only.
- Calculating the size foreach format
- Some styling on the page.

I hope you'll like it and merge it.

Have a nice day.

### CODE REVIEW

**Comment by Wilkins** [comment]
Hi @stefanocudini 
Did you have issues merging this PR ?

**Comment by stefanocudini** [comment]
no sorry github show a message: "this merge cause conflits"  Can you verify please?

**Comment by Wilkins** [comment]
Replaced by this Pull Request : https://github.com/stefanocudini/gpx-simplify-optimizer/pull/11

**Comment by stefanocudini** [comment]
great!

**Pull request closed without merging**
